import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";

export type LLMRole = "system" | "user" | "assistant";
export type LLMMessage = { role: LLMRole; content: string };

export type LLMResult = {
  text: string;
  provider: "openai" | "anthropic" | "offline";
  model: string;
};

export type LLMOptions = {
  temperature?: number;
  maxTokens?: number;
  /** Hint the model to return strict JSON. */
  jsonMode?: boolean;
};

function pickProvider(): "openai" | "anthropic" | "offline" {
  const forced = process.env.LLM_PROVIDER?.toLowerCase();
  if (forced === "openai" && process.env.OPENAI_API_KEY) return "openai";
  if (forced === "anthropic" && process.env.ANTHROPIC_API_KEY) return "anthropic";
  if (forced === "offline") return "offline";
  if (process.env.ANTHROPIC_API_KEY) return "anthropic";
  if (process.env.OPENAI_API_KEY) return "openai";
  return "offline";
}

function defaultModel(p: "openai" | "anthropic" | "offline"): string {
  if (process.env.LLM_MODEL) return process.env.LLM_MODEL;
  if (p === "openai") return "gpt-4o-mini";
  if (p === "anthropic") return "claude-sonnet-4-6";
  return "offline-stub-v1";
}

export async function llmComplete(messages: LLMMessage[], opts: LLMOptions = {}): Promise<LLMResult> {
  const provider = pickProvider();
  const model = defaultModel(provider);
  const temperature = opts.temperature ?? 0.2;
  const maxTokens = opts.maxTokens ?? 2000;

  if (provider === "openai") {
    const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY! });
    const res = await client.chat.completions.create({
      model,
      messages: messages.map((m) => ({ role: m.role, content: m.content })),
      temperature,
      max_tokens: maxTokens,
      response_format: opts.jsonMode ? { type: "json_object" } : undefined,
    });
    return { text: res.choices[0]?.message?.content ?? "", provider, model };
  }

  if (provider === "anthropic") {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });
    const sys = messages.filter((m) => m.role === "system").map((m) => m.content).join("\n\n");
    const conv = messages.filter((m) => m.role !== "system");
    const res = await client.messages.create({
      model,
      system: sys || undefined,
      max_tokens: maxTokens,
      temperature,
      messages: conv.map((m) => ({ role: m.role as "user" | "assistant", content: m.content })),
    });
    const text = res.content
      .map((c) => (c.type === "text" ? c.text : ""))
      .join("")
      .trim();
    return { text, provider, model };
  }

  // Offline deterministic stub — clearly marked so reports show it.
  return { text: offlineStub(messages, opts), provider, model };
}

/**
 * Extract a JSON object from raw LLM text. Tolerates code fences and surrounding prose.
 */
export function extractJson<T = unknown>(text: string): T {
  let t = text.trim();
  const fenceMatch = t.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (fenceMatch) t = fenceMatch[1].trim();
  const firstBrace = t.indexOf("{");
  const lastBrace = t.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) t = t.slice(firstBrace, lastBrace + 1);
  return JSON.parse(t) as T;
}

function offlineStub(messages: LLMMessage[], opts: LLMOptions): string {
  // If JSON is requested, return a deterministic JSON skeleton that downstream
  // schemas will accept. Otherwise return a plain-text stub.
  const last = messages[messages.length - 1]?.content ?? "";
  if (opts.jsonMode || /json/i.test(last)) {
    return JSON.stringify({
      __offline: true,
      summary:
        "LLM key not configured — this is a deterministic offline stub. Set OPENAI_API_KEY or ANTHROPIC_API_KEY in .env.local to enable real analysis.",
      businessOverview:
        "Offline stub: company business overview unavailable without an LLM provider key.",
      revenueModel: "Offline stub: revenue model placeholder.",
      recentNews: "Offline stub: see Recent news on the ticker page.",
      earningsSummary: "Offline stub: latest earnings summary unavailable.",
      bullCase: "Offline stub: configure an LLM key to generate a bull case.",
      bearCase: "Offline stub: configure an LLM key to generate a bear case.",
      keyRisks:
        "Offline stub: this report was not generated by a real LLM. Treat it as illustrative.",
      catalysts: "Offline stub: upcoming catalysts unavailable.",
      valuation: "Offline stub: valuation snapshot unavailable.",
      comps: "Offline stub: comparable companies unavailable.",
      finalView: "avoid",
      confidence: 0.0,
      sources: [],
    });
  }
  return "Offline stub response. Configure OPENAI_API_KEY or ANTHROPIC_API_KEY to enable real LLM output.";
}
